name: news_bloc_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_bloc: ^8.1.4  
  bloc: ^8.1.4
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  flutter_3d_controller: ^1.2.1 
  webview_flutter: ^4.7.0
  get: ^4.6.6
  flutter_animate: ^4.5.0
  flutter_fadein: ^2.0.0
  delayed_display: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


assets:
  -assets/